services:
  database:
    container_name: aquadata
    hostname: aquadata
    image: mysql
    volumes: 
      - .docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 33060:3306
    environment: 
      MYSQL_ROOT_PASSWORD: aquadata@
    
